---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: bookinfo-acm-prod
  name: bookinfo-acm-prod
  namespace: bookinfo-acm-prod
spec:
  clusterSelector:
    matchLabels:
      environment: prd
