
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: bookinfo-acm-dev
  name: bookinfo-acm-dev
  namespace: bookinfo-acm-dev
spec:
  clusterSelector:
    matchLabels:
      environment: prd
