
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-acm-prd
  namespace: bookinfo-acm-prd
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - bookinfo-acm-prd
